### ISSUE TITLE
SET UP - MAIN MENU - organise a number system menu

### ISSUE THREAD

**Issue by 40582347** [Neut-40646470/CourseWork-GroupE#63]
could maybe look like this??
TO BE DISCUSSED

WELCOME
What would you like to see?
Please type a number from the following menu

   1 The population of the world.
   2 The population of a continent.
   3 The population of a region.
   4 The population of a country.
   5 The population of a district.
   6 The population of a city.
Please enter a number: 

You selected 1 to view the population of the world.

How would you like the population to be arranged by?
    
    1 By Country.
    2 By Region.
    3 By Continent.
    4 By District.
    5 By City.
     
You Selected 1 to view population By Country.

How would you like to view By Continent?

1 Smallest to Largest
2 Largest to Smallest

These will each lead on to their own menu

**Comment by callan5820** [comment]
Menu looks good, captures the necessary information as laid out in our backlog

**Comment by eolton** [comment]
Looking good to me - just not sure whether we need to ask the last question - it seems that by default all reports should  display  results by largest population to smallest in which case this would be an additional feature not really requested by the customer...but then again you're the product owner ;)
